name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:    

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23-ea'
          cache: maven            

      - name: Install Maven
        run: |
          sudo apt-get update -y
          sudo apt-get install -y maven
          mvn -version          
          
      - name: Build with Maven
        run: mvn -B clean package -Dmaven.test.skip=true -Dspotless.skip=true --no-transfer-progress

      - name: SonarQube Scan
        run:  |
          mvn -B verify \
            -Dsonar.projectKey=WebGoat \
            -Dsonar.host.url=https://sonar-ee.curvc.com \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.binaries=target/classes \
            org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751
